# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

dotenv:
  - ${HOME}/.env
  - ${XDG_CONFIG_HOME}/zsh/.zshrc
  - ${HOME}/.zshenv

vars:
  HOME_OPS_HOME: "${XDG_DATA_HOME}/automation/home-ops"

includes:
  ansible:
    taskfile: "./scripts/taskfiles/ansible.yaml"
  chez:
    internal: true
    taskfile: "./scripts/taskfiles/chezmoi.yaml"
  validate:
    internal: true
    silent: true
    taskfile: "./scripts/taskfiles/validate.yaml"
  install:
    internal: true
    taskfile: "./scripts/taskfiles/install/install.yaml"
  homeops:
    taskfile: "./scripts/taskfiles/install/homeops.yaml"
  unison:
    internal: true
    taskfile: "./scripts/taskfiles/unison.yaml"

tasks:
  build:jar:
    desc: Build the jar
    silent: false
    internal: true
    summary: |
      To ensure cross-platform compatibility, the jar is built using the Gradle wrapper and as a non AoT jar
    cmds:
      - >-
        ./gradlew bootJar
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops/scripts/spring-cli"

  build:script:
    desc: Build the shell script to deploy
    silent: false
    internal: false
    cmds:
      - cmd: ./build.sh
    dir: "scripts/shell"

  mcv:pack:
    desc: Pack all the projects
    silent: false
    summary: |
      This task packs all the projects locally into a script with a jar attachment to install everything on the target system
    deps:
      - task: install:node
      - task: install:python
      - task: install:brew
      - task: build:jar
    cmds:
      - cmd: test -d /tmp/mcv || rm -rf /tmp/mcv
      - cmd: mkdir -p /tmp/mcv/dist
      # Clean build artifacts and temporary directories in the automation data directory
      - cmd: |
          find {{.XDG_DATA_HOME}}/automation \
          -type d \( -name "node_modules" -o -name "dist" -o -name "target" -o -name "__pycache__" -o -name "*.egg-info" -o -name ".venv" \) \
          -exec rm -rf {} +
      # Create archive
      - cmd: >-
          tar -czf /tmp/mcv/dist/payload.tar.gz -C {{.XDG_CONFIG_HOME}} {{.XDG_DATA_HOME}}/trapper_keeper {{.ANSIBLE_HOME}}
      # Create executable
      - cmd: >-

          {{.XDG_DATA_HOME}}/automation/home-ops/scripts/spring-cli/build/libs/home-ops.jar > /tmp/mcv/dist/mcv.run
          && chmod +x /tmp/mcv/dist/mcv.run
      # Create tarball
      - cmd: >-
          tar -czf /tmp/mcv.tar.gz -C /tmp/mcv/dist /tmp/mcv/dist/payload.tar.gz

  mcv:unpack:
    desc: Unpack all the projects
    silent: true
    summary: |
      This task unpacks all the projects locally from a script with a jar attachment
    cmds:
      # Unpack the tarball
      - cmd: >-
          tar -xzf /tmp/mcv.tar.gz -C /tmp/mcv/dist
      # Run the script
      - cmd: >-
          /tmp/mcv/dist/mcv.run

  shell:
    desc: Start the Spring Shell Service and console
    silent: true
    deps:
      - task: build:jar
    summary: |
      This task runs the shell script
    cmds:
      - cmd: >-
          java -jar {{.XDG_DATA_HOME}}/automation/home-ops/scripts/spring-cli/build/libs/home-ops.jar
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops/scripts/spring-cli"

  sync:
    desc: Sync the XDG Folders to the Google Drive Share
    cmds:
      - cmd: rsync -avzPh ~/.config ~/Library/CloudStorage/GoogleDrive-jhettenh@gmail.com/My\ Drive/.config
        platforms:
          - darwin
      - cmd: rsync -avzPh ~/.config ~/Library/CloudStorage/GoogleDrive-jhettenh@gmail.com/My\ Drive/.local
        platforms:
          - darwin
      - cmd: rsync -avzPh ~/.config $HOME/.local/state/gdrive
        platforms:
          - linux
      - cmd: rsync -avzPh ~/.local $HOME/.local/state/gdrive
        platforms:
          - linux
