# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

dotenv:
  - ${HOME}/.env
  - ${HOME}/.zshrc
  - ${HOME}/.zshenv

includes:
  deploy:
    taskfile: "./scripts/taskfiles/deploy.yaml"
  ansible:
    taskfile: "./scripts/taskfiles/ansible.yaml"
  chez:
    taskfile: "./scripts/taskfiles/chezmoi.yaml"
  kp:
    taskfile: "./scripts/taskfiles/keepassxc.yaml"
  validate:
    internal: true
    taskfile: "./scripts/taskfiles/validate.yaml"
  install:
    internal: true
    taskfile: "./scripts/taskfiles/install/install.yaml"
  git:
    internal: true
    taskfile: "./scripts/taskfiles/git.yaml"
  unison:
    taskfile: "./scripts/taskfiles/unison.yaml"

tasks:
  nx:show:
    desc: Show the available nx commands
    run: once
    silent: true
    cmds:
      - npx nx show projects --affected

  #  deploy:local:
  #    desc: Deploy the applications locally
  #    cmds:
  #      - task: scripts:deploy

  #  init:
  #    desc: Initialize all the projects
  #    run: once
  #    summary: |
  #      This task initializes all the projects locally
  #    cmds:
  #      - npx nx run-many --target=init --parallel --all --verbose
  #    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  lint:
    desc: Lint all the projects
    interactive: true
    run: once
    deps:
      - task: install:node
    summary: |
      This task lints all the projects locally
    cmds:
      - npx nx run-many --target=lint --parallel --all --verbose --fix
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  install:
    desc: Install all the projects and any missing tools
    run: once
    deps:
      - task: build
      - task: install:pipx
    summary: |
      This task installs all npm/poetry packages
    cmds:
      - cmd: npx nx run-many --target=install --parallel --all
      - cmd: npx nx run-many --target=install-bin --parallel --all

    #      - |
    #        cp ./sea-config.json ./dist/apps/home-ops/sea-config.json
    #        source ${XDG_DATA_HOME}/nvm/nvm.sh; nvm use --lts
    #        cd ./dist/apps/home-ops && node --experimental-sea-config sea-config.json
    #        cp $(command -v node) home-ops
    #
    #        if [[ {{OS}} == "darwin" ]]; then
    #          codesign --remove-signature home-ops
    #          npx postject home-ops NODE_SEA_BLOB sea-prep.blob --macho-segment-name NODE_SEA --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8
    #        else
    #          npx postject home-ops NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8
    #        fi
    # dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  build:
    run: once
    # deps:
    #   - task: lint
    desc: Build all the projects
    summary: |
      This task builds all the projects locally
    cmds:
      - npx nx run-many --target=build --parallel --all
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  test:
    run: once
    desc: Test all the projects
    deps:
      - task: lint
      - task: build
    summary: |
      This task tests all the projects locally
    cmds:
      - npm run test:all
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  test:functional:
    run: once
    desc: Test Home Ops Using Proxmox and Ansible
    deps:
      - task: mcv:unpack
    cmds:
      - task: pya:ans:run
        vars:
          CLI_ARGS: "create-lxc"
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  #  update:
  #    desc: Update all the project libraries
  #    run: once
  #    summary: |
  #      This task updates all the projects locally
  #    cmds:
  #      - npx nx migrate latest
  #      - npx nx migrate @nxlv/python:latest
  #      - npx npm-check-updates -u
  #      - echo "Run 'npm install' to update the packages"
  #    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  sync:
    desc: Sync all the projects
    run: once
    preconditions:
      - test $(command -v trapper-keeper)
    deps:
      - task: install:tools
    summary: |
      This task runs all synchronization tasks
    cmds:
      - task: git:sync
      - task: chez:sync
      - task: deploy:sync
      # - task: install:sync
      - task: ansible:sync
      - task: unison:sync
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  mcv:pack:
    desc: Pack all the projects
    summary: |
      This task packs all the projects locally into a script with a jar attachment to install everything on the target system
    deps:
      - task: validate:internal:xdg
      - task: validate:internal:scripts
      - task: install:node
      - task: install:python
      - task: install:brew
    cmds:
      - cmd: mkdir -p /tmp/mcv/dist
      # Clean build artifacts and temporary directories in the automation data directory
      - cmd: |
          find {{.XDG_DATA_HOME}}/automation \
          -type d \( -name "node_modules" -o -name "dist" -o -name "target" -o -name "__pycache__" -o -name "*.egg-info" \) \
          -exec rm -rf {} +
      # Create archive
      - cmd: >-
          tar -czf /tmp/mcv/dist/mcv.tar.gz -C {{.XDG_CONFIG_HOME}} {{.XDG_DATA_HOME}}/trapper_keeper {{.XDG_DATA_HOME}}/unison {{.XDG_DATA_HOME}}/automation {{.ANSIBLE_HOME}}
      # Create final executable
      - cmd: >-
          cat {{.XDG_DATA_HOME}}/automation/home-ops/scripts/shell/bin/dasbootstrap.sh
          {{.XDG_DATA_HOME}}/automation/home-ops/scripts/shell/bin/user_install.sh
          $(find {{.XDG_DATA_HOME}}/automation/home-ops/scripts/spring-cli/build/libs -name "home-ops.jar")
          /tmp/mcv/dist/mcv.tar.gz > /tmp/mcv/dist/mcv.run &&
          chmod +x /tmp/mcv/dist/mcv.run

  angularapp:create:
    desc: Create a new Angular application
    summary: |
      This task creates a new Angular application, skipping test and framework defaults for flexibility
    cmds:
      - >-
        npx nx generate @nx/angular:application --directory apps/{{.PROJ_NAME}} --bundler esbuild
        --standalone false --e2eTestRunner playwright --unitTestRunner jest --style less
        --name {{.PROJ_NAME}} --ssr false --verbose
    vars:
      PROJ_NAME:
        sh: "echo $(gum input --placeholder 'Project Name')"
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  nodeapp:create:
    desc: Create a new NodeJS application
    summary: |
      This task creates a new NodeJS application, skipping test and framework defaults for flexibility
    cmds:
      - >-
        npx nx generate @nx/node:application --directory apps/{{.PROJ_NAME}} --bundler esbuild --framework none
        --name {{.PROJ_NAME}} --docker true --e2eTestRunner none --js false --unitTestRunner none
        --projectNameAndRootFormat as-provided --verbose
    #      - test -f ./apps/{{.PROJ_NAME}}/eslint.config.js && rm ./apps/{{.PROJ_NAME}}/eslint.config.js
    #      - mv ./apps/{{.PROJ_NAME}}/main.ts ./apps/{{.PROJ_NAME}}/main.mts
    #      - ln -sf ./config/apps/tsconfig.json ./apps/{{.PROJ_NAME}}/tsconfig.json
    #      - ln -sf ./config/apps/tsconfig.app.json ./apps/{{.PROJ_NAME}}/tsconfig.app.json
    #      - ln -sf ./config/apps/tsconfig.spec.json ./apps/{{.PROJ_NAME}}/tsconfig.spec.json
    vars:
      PROJ_NAME:
        sh: "echo $(gum input --placeholder 'Project Name')"
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  nodelib:create:
    desc: Create a new NodeJS library
    summary: |
      This task creates a new NodeJS library, skipping test and framework defaults for flexibility
    cmds:
      - >-
        npx nx generate @nx/node:library --directory libs/{{.PROJ_NAME}} --bundler esbuild --framework none
        --name {{.PROJ_NAME}} --docker true --e2eTestRunner none --js false --unitTestRunner none
        --projectNameAndRootFormat as-provided --verbose
    vars:
      PROJ_NAME:
        sh: "echo $(gum input --placeholder 'Library Name')"
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"

  pyapp:create:
    desc: Create a new Python application
    summary: |
      This task creates a new Python application
    cmds:
      - >-
        npx nx generate @nxlv/python:poetry-project {{.PROJ_NAME}} --projectType application --packageName {{.PROJ_NAME}}
        --directory pyapps/{{.PROJ_NAME}} --moduleName {{.MODULE_NAME}}  --pyprojectPythonDependency '>=3.11,<4.0'
        --linter ruff --projectNameAndRootFormat as-provided
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"
    vars:
      PROJ_NAME:
        sh: "echo $(gum input --placeholder 'Project Name')"
      MODULE_NAME:
        sh: "echo $(gum input --placeholder 'Module Name: Usually the same as the project name with an underscore')"

  pylib:create:
    desc: Create a new Python library
    summary: |
      This task creates a new Python library
    cmds:
      - >-
        npx nx generate @nxlv/python:poetry-project {{.PROJ_NAME}} --projectType library --packageName {{.PROJ_NAME}}
        --directory pylibs/{{.PROJ_NAME}} --moduleName {{.MODULE_NAME}}  --pyprojectPythonDependency '>=3.11,<4.0'
        --linter ruff --projectNameAndRootFormat as-provided
    dir: "{{.XDG_DATA_HOME}}/automation/home-ops"
    vars:
      PROJ_NAME:
        sh: "echo $(gum input --placeholder 'Library Name')"
      MODULE_NAME:
        sh: "echo $(gum input --placeholder 'Module Name: Usually the same as the library name with an underscore')"
