version: "3"

tasks:
  build:
    desc: "Build Trapper Keeper"
    cmds:
      - nx build trapper-keeper

  install:
    desc: "Install Trapper Keeper"
    cmds:
      - pipx install . trapper-keeper --include-deps
