- name: Update Proxmox nodes on the network
  hosts: |
    mandorallen.local.technohouser.com
    mara.local.technohouser.com
    minfilia.local.technohouser.com
    noctis.local.technohouser.com
    salmissra.local.technohouser.com
    yshtola.local.technohouser.com
  remote_user: root
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
