
spring:
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 3600000
  data:
    jpa:
      database-platform: org.hibernate.dialect.SQLiteDialect
      hibernate:
        ddl-auto: create
        show-sql: true
  datasource:
    driver-class-name: "org.sqlite.JDBC"
    url: "jdbc:sqlite:${XDG_DATA_HOME}/home-ops/db.sqlite"
  main:
    banner-mode: off
