spring:
  toml:
    enabled: true
  shell:
    interactive:
      enabled: true
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 3600000
  config:
    import:
      - "file://${XDG_CONFIG_HOME}/home-ops/host.json"
      - "file://${XDG_CONFIG_HOME}/home-ops/default.toml"
  data:
    jpa:
      database-platform: org.hibernate.dialect.SQLiteDialect
      hibernate:
        ddl-auto: create
        show-sql: true

  datasource:
    driver-class-name: "org.sqlite.JDBC"
    url: "jdbc:sqlite:${XDG_DATA_HOME}/home-ops/db.sqlite"
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator



