[colors]
  base0 = "#131313"
  base1 = "#191919"
  base2 = "#222222"
  base3 = "#363537"
  base4 = "#525053"
  base5 = "#69676c"
  base6 = "#8b888f"
  base7 = "#bab6c0"
  base8 = "#f7f1ff"
  base8x0c = "#2b2b2b"
  blue = "#5ad4e6"
  green = "#7bd88f"
  orange = "#fd9353"
  purple = "#948ae3"
  red = "#fc618d"
  yellow = "#fcd566"

[express]
  port = 3000
